name: Tests

on: push

jobs:
  lint:
    name: Test code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install dependencies
        run: make setup
      - name: Run tests
        if: ${{ always() }}
        run: make test
      - name: Debug tests
        uses: actions/upload-artifact@v2
        with:
            name: debug-tests
            path: storage/tests.html
      - name: Download a debug-tests artifact
        uses: actions/download-artifact@v2
        with:
          name: debug-tests
